credentials:
  sashi:
    free_api_key: 
    free_secret_key: 
    api_key: 
    secret_key: 
    username : 
    password : 
    authenticator_token : LRSH4P4ZWCVFACEWP7FYDL5YAEPPFGXD
  madhu:
    api_key: 
    secret_key: 
    username: 
    password: 
    authenticator_token: MS7TBL4ODBG34FPIMXDXECYYZHBPOLMB
  sakhi:
    api_key: 
    secret_key: 
    username: 
    password: 
    authenticator_token: MS7TBL4ODBG34FPIMXDXECYYZHBPOLMB
