credentials:
  sashi:
    free_api_key: f9dtnoqozzcg5a51
    free_secret_key: dz6a70kj5gdvo84k16gexspsgwyo159e
    api_key: h2et7ziru3p6yhlm
    secret_key: 6k24i3s9ho7bzqwrfuyfwntlv2wrm9b4
    username : OL5402
    password : Skanth123$
    authenticator_token : LRSH4P4ZWCVFACEWP7FYDL5YAEPPFGXD
  madhu:
    api_key: erenpd2psfhkugz4
    secret_key: flhvf7rd4pa3jqhq9g5gsbbj4rny83fi
    username: HOZ563
    password: Arepalli123$
    authenticator_token: MS7TBL4ODBG34FPIMXDXECYYZHBPOLMB
  sakhi:
    api_key: erenpd2psfhkugz4
    secret_key: flhvf7rd4pa3jqhq9g5gsbbj4rny83fi
    username: XBY921
    password: Arepalli123$
    authenticator_token: MS7TBL4ODBG34FPIMXDXECYYZHBPOLMB
