adjust_at: 30
adjust_hedges: true
adjustment: true
close_on_stoploss: false
close_on_trailprofit: false
delay: 30
last_watched: 2026-04-15 14:08
max_loss_multiplier: 10
minimum_distance_from_index: 400
trail_profit_threshold: 3
trailing_profit_multiplier: 3
users: sashi
